from rest_framework.status import HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND

ERROR_DATA_DESTINATION_DOES_NOT_EXIST = (
    "ERROR_DATA_DESTINATION_DOES_NOT_EXIST",
    HTTP_404_NOT_FOUND,
    "{e}",
)
ERROR_DATA_DESTINATION_PURPOSE_NOT_ALLOWED = (
    "ERROR_DATA_DESTINATION_PURPOSE_NOT_ALLOWED",
    HTTP_400_BAD_REQUEST,
    "{e}",
)
ERROR_INVALID_DATA_DESTINATION_KEY = (
    "ERROR_INVALID_DATA_DESTINATION_KEY",
    HTTP_400_BAD_REQUEST,
    "The provided object key is not valid for this destination.",
)
