# This is the recommended way of running Baserow using docker-compose for most users.
# See https://github.com/carneirofc/baserow for more details.
services:
  baserow:
    container_name: baserow
    image: ghcr.io/carneirofc/baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: 'http://localhost'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
