import hashlib
import hmac
from typing import List, Optional, Tuple

from django.contrib.auth.models import AbstractUser
from django.db.models import QuerySet
from django.utils import timezone

from baserow.core.handler import CoreHandler
from baserow.core.models import Workspace
from baserow.core.utils import random_string

from .exceptions import (
    ApiClientDoesNotBelongToUser,
    ApiClientDoesNotExist,
    ApiClientKeyDoesNotExist,
    InvalidApiClientScope,
    MaximumUniqueApiClientKeyTriesError,
)
from .models import ApiClient, ApiClientKey
from .operations import (
    CreateApiClientOperationType,
    DeleteApiClientOperationType,
    ListApiClientsOperationType,
    ReadApiClientOperationType,
    UpdateApiClientOperationType,
)
from .scopes import ALL_SCOPES

PREFIX_LENGTH = 8
SECRET_LENGTH = 40


class ApiClientHandler:
    def hash_secret(self, secret: str) -> str:
        """
        Hashes the secret part of a key.

        A plain SHA-256 is used instead of a password hasher on purpose. The secret is
        generated by us with 40 characters out of a 62 character alphabet (~238 bits of
        entropy), so it is not brute forceable and does not need the key stretching a
        password hasher provides. Key stretching would instead add its full cost to
        every single authenticated API request.

        :param secret: The plain secret part of a key.
        :return: The hex encoded hash of the secret.
        """

        return hashlib.sha256(secret.encode("utf-8")).hexdigest()

    def generate_unique_prefix(self, max_tries: int = 1000) -> str:
        """
        Generates a prefix that is not yet used by another key.

        :raises MaximumUniqueApiClientKeyTriesError: When no unique prefix could be
            generated within `max_tries` attempts.
        :return: A unique prefix.
        """

        for _ in range(max_tries):
            prefix = random_string(PREFIX_LENGTH)
            if not ApiClientKey.objects.filter(prefix=prefix).exists():
                return prefix

        raise MaximumUniqueApiClientKeyTriesError(
            f"Tried {max_tries} key prefixes, but none of them are unique."
        )

    def validate_scopes(self, scopes: List[str]) -> List[str]:
        """
        Checks that every provided scope is a known scope.

        :param scopes: The scopes to validate.
        :raises InvalidApiClientScope: When an unknown scope is provided.
        :return: The deduplicated scopes, in the canonical order.
        """

        unknown = [scope for scope in scopes if scope not in ALL_SCOPES]
        if unknown:
            raise InvalidApiClientScope(
                f"The scopes {', '.join(sorted(unknown))} are not valid. Valid scopes "
                f"are: {', '.join(ALL_SCOPES)}."
            )

        return [scope for scope in ALL_SCOPES if scope in scopes]

    def list_clients(self, user: AbstractUser, workspace_id: int) -> QuerySet:
        """
        Lists the API clients of a workspace that belong to the given user.

        :param user: The user on whose behalf the clients are listed.
        :param workspace_id: The workspace to list the clients of.
        :return: A queryset of API clients.
        """

        workspace = CoreHandler().get_workspace(workspace_id)
        CoreHandler().check_permissions(
            user,
            ListApiClientsOperationType.type,
            workspace=workspace,
            context=workspace,
        )

        return (
            ApiClient.objects.filter(workspace=workspace, user=user)
            .select_related("workspace")
            .prefetch_related("keys")
        )

    def get_client(
        self, user: AbstractUser, client_id: int, base_queryset: QuerySet = None
    ) -> ApiClient:
        """
        Fetches a single API client and checks that the user may read it.

        :param user: The user on whose behalf the client is requested.
        :param client_id: The id of the requested client.
        :param base_queryset: The base queryset to select the client from.
        :raises ApiClientDoesNotExist: When the client does not exist or does not
            belong to the user.
        :return: The fetched client.
        """

        if base_queryset is None:
            base_queryset = ApiClient.objects

        try:
            client = base_queryset.select_related("workspace").get(
                id=client_id, user=user
            )
        except ApiClient.DoesNotExist:
            raise ApiClientDoesNotExist(
                f"The API client with id {client_id} does not exist."
            )

        CoreHandler().check_permissions(
            user,
            ReadApiClientOperationType.type,
            workspace=client.workspace,
            context=client,
        )

        return client

    def create_client(
        self,
        user: AbstractUser,
        workspace: Workspace,
        name: str,
        scopes: List[str],
    ) -> ApiClient:
        """
        Creates a new API client in the given workspace.

        :param user: The user on whose behalf the client is created and as whom the
            client will act.
        :param workspace: The workspace the client is limited to.
        :param name: The human readable name of the client.
        :param scopes: The scopes the client is limited to.
        :return: The created client.
        """

        CoreHandler().check_permissions(
            user,
            CreateApiClientOperationType.type,
            workspace=workspace,
            context=workspace,
        )

        return ApiClient.objects.create(
            name=name,
            workspace=workspace,
            user=user,
            scopes=self.validate_scopes(scopes),
        )

    def update_client(
        self,
        user: AbstractUser,
        client: ApiClient,
        name: Optional[str] = None,
        scopes: Optional[List[str]] = None,
        is_active: Optional[bool] = None,
    ) -> ApiClient:
        """
        Updates an existing API client.

        :param user: The user on whose behalf the client is updated.
        :param client: The client to update.
        :param name: The new name, if provided.
        :param scopes: The new scopes, if provided.
        :param is_active: The new active state, if provided.
        :raises ApiClientDoesNotBelongToUser: When the client belongs to another user.
        :return: The updated client.
        """

        self._raise_if_not_owner(user, client)

        CoreHandler().check_permissions(
            user,
            UpdateApiClientOperationType.type,
            workspace=client.workspace,
            context=client,
        )

        if name is not None:
            client.name = name
        if scopes is not None:
            client.scopes = self.validate_scopes(scopes)
        if is_active is not None:
            client.is_active = is_active

        client.save()
        return client

    def delete_client(self, user: AbstractUser, client: ApiClient):
        """
        Deletes an API client and all of its keys.

        :param user: The user on whose behalf the client is deleted.
        :param client: The client to delete.
        :raises ApiClientDoesNotBelongToUser: When the client belongs to another user.
        """

        self._raise_if_not_owner(user, client)

        CoreHandler().check_permissions(
            user,
            DeleteApiClientOperationType.type,
            workspace=client.workspace,
            context=client,
        )

        client.delete()

    def create_key(
        self,
        user: AbstractUser,
        client: ApiClient,
        name: str = "",
        expires_on=None,
    ) -> Tuple[ApiClientKey, str]:
        """
        Issues a new key for the given client.

        :param user: The user on whose behalf the key is created.
        :param client: The client the key belongs to.
        :param name: An optional label for the key.
        :param expires_on: An optional moment after which the key stops working.
        :raises ApiClientDoesNotBelongToUser: When the client belongs to another user.
        :return: A tuple of the created key and the plain key string. The plain string
            is the only moment the secret is available, it is not stored.
        """

        self._raise_if_not_owner(user, client)

        CoreHandler().check_permissions(
            user,
            UpdateApiClientOperationType.type,
            workspace=client.workspace,
            context=client,
        )

        prefix = self.generate_unique_prefix()
        secret = random_string(SECRET_LENGTH)

        key = ApiClientKey.objects.create(
            api_client=client,
            name=name,
            prefix=prefix,
            hashed_secret=self.hash_secret(secret),
            expires_on=expires_on,
        )

        return key, f"{prefix}.{secret}"

    def get_key(self, user: AbstractUser, key_id: int) -> ApiClientKey:
        """
        Fetches a single key that belongs to one of the user's clients.

        :param user: The user on whose behalf the key is requested.
        :param key_id: The id of the requested key.
        :raises ApiClientKeyDoesNotExist: When the key does not exist or belongs to
            another user.
        :return: The fetched key.
        """

        try:
            return ApiClientKey.objects.select_related(
                "api_client", "api_client__workspace"
            ).get(id=key_id, api_client__user=user)
        except ApiClientKey.DoesNotExist:
            raise ApiClientKeyDoesNotExist(
                f"The API client key with id {key_id} does not exist."
            )

    def revoke_key(self, user: AbstractUser, key: ApiClientKey) -> ApiClientKey:
        """
        Revokes a key. The record is kept so the revocation stays auditable.

        :param user: The user on whose behalf the key is revoked.
        :param key: The key to revoke.
        :return: The revoked key.
        """

        self._raise_if_not_owner(user, key.api_client)

        CoreHandler().check_permissions(
            user,
            UpdateApiClientOperationType.type,
            workspace=key.api_client.workspace,
            context=key.api_client,
        )

        if key.revoked_on is None:
            key.revoked_on = timezone.now()
            key.save(update_fields=["revoked_on"])

        return key

    def authenticate(self, raw_key: str) -> ApiClient:
        """
        Resolves a raw `prefix.secret` key into the API client it authenticates.

        :param raw_key: The key as provided in the Authorization header.
        :raises ApiClientKeyDoesNotExist: When the key is malformed, unknown, revoked,
            expired, or when its client is inactive.
        :return: The authenticated API client.
        """

        prefix, separator, secret = raw_key.partition(".")

        if not separator or not prefix or not secret:
            raise ApiClientKeyDoesNotExist("The provided key is malformed.")

        try:
            key = ApiClientKey.objects.select_related(
                "api_client", "api_client__workspace", "api_client__user"
            ).get(prefix=prefix)
        except ApiClientKey.DoesNotExist:
            raise ApiClientKeyDoesNotExist("The provided key does not exist.")

        if not hmac.compare_digest(key.hashed_secret, self.hash_secret(secret)):
            raise ApiClientKeyDoesNotExist("The provided key does not exist.")

        if not key.is_usable:
            raise ApiClientKeyDoesNotExist("The provided key is revoked or expired.")

        if not key.api_client.is_active:
            raise ApiClientKeyDoesNotExist("The API client is not active.")

        ApiClientKey.objects.filter(id=key.id).update(last_used_on=timezone.now())

        return key.api_client

    def _raise_if_not_owner(self, user: AbstractUser, client: ApiClient):
        if user.id != client.user_id:
            raise ApiClientDoesNotBelongToUser(
                "The user is not authorized to manage this API client."
            )
