apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baserow.fullname" . }}-celery
  labels:
    {{- include "baserow.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: {{ .Values.replicaCount.celery }}
  selector:
    matchLabels:
      {{- include "baserow.componentSelectorLabels" (dict "root" . "component" "celery") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "baserow.componentSelectorLabels" (dict "root" . "component" "celery") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "baserow.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery
          image: {{ include "baserow.image.backend" . }}
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          args: ["celery-worker"]
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          envFrom:
            {{- include "baserow.envFrom" . | nindent 12 }}
          env:
            {{- include "baserow.secretEnv" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /baserow/backend/docker/docker-entrypoint.sh
                - celery-worker-healthcheck
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources.celery | nindent 12 }}
          volumeMounts:
            {{- include "baserow.tmpVolumeMounts" . | nindent 12 }}
            {{- if not .Values.objectStorage.enabled }}
            - name: media
              mountPath: /baserow/media
            {{- end }}
      volumes:
        {{- include "baserow.tmpVolumes" . | nindent 8 }}
        {{- if not .Values.objectStorage.enabled }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "baserow.fullname" . }}-media
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
