{{- if .Values.ingress.enabled }}
{{- $fullname := include "baserow.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "baserow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.backendPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-backend
                port:
                  number: 8000
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-web-frontend
                port:
                  number: 3000
{{- end }}
