# Generated by Django 5.2.15 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0075_container_element_positioning_behaviour"),
    ]

    operations = [
        migrations.AddField(
            model_name="iframeelement",
            name="allow_same_origin",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether a trusted external URL can access its own origin.",
            ),
        ),
    ]
