# Generated by Django 5.2.14 on 2026-06-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0034_corestartworkflowactionnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreGotoActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
    ]
