# Generated by Django 5.2.15 on 2026-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0212_data_sync_delete_unmatched_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formview',
            name='mode',
            field=models.TextField(choices=[("form", "form")], default="form", help_text="Configurable mode of the form.", max_length=64),
        ),
    ]
