# Generated by Django 5.2.17 on 2026-09-08 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_api_clients_and_backup_schedules'),
        ('database', '0213_alter_formview_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportjob',
            name='mode',
            field=models.CharField(choices=[('append', 'Append'), ('upsert', 'Upsert'), ('replace', 'Replace')], default='append', help_text='Whether the data is appended to the table, upserted into it or used to replace its contents. Only applies to imports into an existing table.', max_length=16),
        ),
        migrations.CreateModel(
            name='TableImportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.TextField(blank=True, default='')),
                ('database_name', models.TextField(blank=True, default='')),
                ('table_name', models.TextField(blank=True, default='')),
                ('user_email', models.TextField(blank=True, default='', help_text='The email of the user at the time of the import.')),
                ('user_ip_address', models.GenericIPAddressField(help_text='The IP address the import was requested from.', null=True)),
                ('mode', models.CharField(choices=[('append', 'Append'), ('upsert', 'Upsert'), ('replace', 'Replace')], default='append', help_text="Whether the file was appended, upserted or used to replace the table's contents.", max_length=16)),
                ('importer_type', models.TextField(blank=True, default='', help_text='The frontend importer identifier used to parse the file.')),
                ('original_file_name', models.TextField(blank=True, default='', help_text='The original name of the uploaded file.')),
                ('payload_sha256', models.CharField(blank=True, default='', help_text='SHA-256 of the normalized row payload that was imported.', max_length=64)),
                ('payload_bytes', models.PositiveBigIntegerField(default=0, help_text='Size in bytes of the normalized row payload.')),
                ('field_mapping', models.JSONField(default=list, help_text='One {column, field_id} entry per column of the imported file, in file order.')),
                ('upsert_field_ids', models.JSONField(default=list, help_text='The field ids used to match imported rows against existing rows.')),
                ('rows_in_file', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_deleted', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('trashed_rows_entry_id', models.PositiveIntegerField(help_text='The trash entry holding the rows a replace removed, so the previous contents can be restored.', null=True)),
                ('row_history_truncated', models.BooleanField(default=False, help_text='Whether per-row history was capped by BASEROW_MAX_ROW_HISTORY_ENTRIES_PER_IMPORT.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='running', max_length=16)),
                ('error', models.TextField(blank=True, default='', help_text='The error that made the import fail.')),
                ('report', models.JSONField(default=dict, help_text='A copy of the per-row error report.')),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(null=True)),
                ('database', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_import_records', to='database.database')),
                ('job', models.ForeignKey(help_text='The import job this record describes, while it still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='database.fileimportjob')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='database.table')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_import_records', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_import_records', to='core.workspace')),
            ],
            options={
                'ordering': ('-started_on', '-id'),
                'indexes': [models.Index(fields=['table', '-started_on'], name='database_ta_table_i_582462_idx'), models.Index(fields=['workspace', '-started_on'], name='database_ta_workspa_6b39c5_idx')],
            },
        ),
    ]
