# Generated by Django 5.2.17 on 2026-09-13 21:15

import baserow.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_backup_destinations'),
        ('database', '0213_alter_formview_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableExportSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The human readable name of the schedule.', max_length=100)),
                ('table_ids', models.JSONField(blank=True, default=None, help_text='The tables to export. Null means every table of the database.', null=True)),
                ('destination', models.CharField(help_text='The name of the env-declared data destination to write to.', max_length=100)),
                ('cron', models.CharField(help_text='A five field crontab expression (minute hour day_of_month month day_of_week) describing when the export runs.', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text='The timezone the cron expression is evaluated in.', max_length=64)),
                ('full_every_n', models.PositiveIntegerField(default=24, help_text='Force a full export after this many incremental ones. Zero only exports fully when required, for example after a schema change.')),
                ('column_naming', models.CharField(choices=[('field_id', 'field_id'), ('field_name', 'field_name')], default='field_id', help_text='How Parquet columns are named: `field_id` (stable across renames) or `field_name`.', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive schedules are skipped by the periodic task.')),
                ('next_run_on', models.DateTimeField(db_index=True, help_text='The next moment this schedule is due.')),
                ('last_run_on', models.DateTimeField(blank=True, help_text='The last moment this schedule ran.', null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='The errors of the last run, empty when it was fine.')),
                ('database', models.ForeignKey(help_text='The database whose tables are exported.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.database')),
                ('user', models.ForeignKey(help_text='The user the exports run on behalf of.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace the database belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TableExportRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=16)),
                ('state', models.CharField(default='running', max_length=16)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('watermark_from', models.DateTimeField(blank=True, null=True)),
                ('watermark_to', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.BigIntegerField(default=0)),
                ('object_prefix', models.CharField(blank=True, default='', max_length=1024)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='database.table')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='database.tableexportschedule')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TableExportState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watermark', models.DateTimeField(blank=True, help_text='The snapshot moment of the last successful export.', null=True)),
                ('last_full_on', models.DateTimeField(blank=True, null=True)),
                ('incrementals_since_full', models.PositiveIntegerField(default=0)),
                ('schema_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='database.tableexportschedule')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.table')),
            ],
            options={
                'unique_together': {('schedule', 'table')},
            },
        ),
    ]
