from rest_framework.status import HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND

ERROR_TABLE_EXPORT_SCHEDULE_DOES_NOT_EXIST = (
    "ERROR_TABLE_EXPORT_SCHEDULE_DOES_NOT_EXIST",
    HTTP_404_NOT_FOUND,
    "The requested table export schedule does not exist.",
)
ERROR_INVALID_TABLE_EXPORT_SCHEDULE_CRON = (
    "ERROR_INVALID_TABLE_EXPORT_SCHEDULE_CRON",
    HTTP_400_BAD_REQUEST,
    "{e}",
)
ERROR_TABLE_EXPORT_TABLES_NOT_IN_DATABASE = (
    "ERROR_TABLE_EXPORT_TABLES_NOT_IN_DATABASE",
    HTTP_400_BAD_REQUEST,
    "{e}",
)
