# Generated by Django 5.2.14 on 2026-06-24 09:14

import baserow.core.formula.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0035_coregotoactionnode'),
        ('core', '0114_alter_workspaceinvitation_message'),
        ('integrations', '0031_corestartworkflowservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreGotoService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('condition', baserow.core.formula.field.FormulaField(blank=True, default='', help_text='The formula that must evaluate to true for the jump to the destination service to be followed.', null=True)),
                ('destination_service', models.ForeignKey(help_text='The service to jump to when the condition evaluates to true.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.service')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.service',),
        ),
    ]
