# Generated by Django 5.2.15 on 2026-07-10 10:45

import baserow.contrib.integrations.local_baserow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
        ('integrations', '0031_corestartworkflowservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBaserowTableServiceFilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='Indicates whether all the rows should apply to all filters (AND) or to any filter (OR) in the group to be shown.', max_length=3)),
                ('parent_group', models.ForeignKey(default=None, help_text='The parent filter group, allowing groups to be nested. If null, the group is directly under the service.', null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.localbaserowtableservicefiltergroup')),
                ('service', models.ForeignKey(help_text='The service which this filter group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='service_filter_groups', to='core.service')),
            ],
            options={
                'ordering': ('id',),
            },
            managers=[
                ('objects', baserow.contrib.integrations.local_baserow.models.LocalBaserowTableServiceRefinementManager()),
            ],
        ),
        migrations.AddField(
            model_name='localbaserowtableservicefilter',
            name='group',
            field=models.ForeignKey(db_default=None, default=None, help_text='The filter group to which the filter applies. If null, the filter applies directly to the service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='integrations.localbaserowtableservicefiltergroup'),
        ),
    ]
