# Generated by Django 5.2.15 on 2026-07-16 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCAuthProviderModel',
            fields=[
                ('authprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.authprovidermodel')),
                ('name', models.CharField(help_text='The stable name of the env-configured OIDC provider.', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.authprovidermodel',),
        ),
    ]
