# Generated by Django 5.2.15 on 2026-07-20 23:18

import baserow.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_settings_application_feature_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('operations', models.ManyToManyField(blank=True, help_text='The operations a WorkspaceUser assigned this role is allowed to perform.', related_name='roles', to='core.operation')),
                ('workspace', models.ForeignKey(help_text='The workspace this role belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.workspace')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='role',
            field=models.ForeignKey(db_default=None, help_text="The custom role restricting this member's operations. NULL means no custom role is assigned, i.e. today's full-member access.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_users', to='core.role'),
        ),
    ]
