# Generated by Django 5.2.15 on 2026-07-29 19:31

import baserow.core.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_add_role_model_and_workspace_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The human readable name of the API client.', max_length=100)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, help_text='The scopes that requests made with this client are limited to.', size=None)),
                ('is_active', models.BooleanField(default=True, help_text='If false, every key of this client is rejected without being deleted.')),
                ('user', models.ForeignKey(help_text="The user that owns the API client. Requests made with one of the client's keys are performed on behalf of this user.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Only the resources of this workspace can be accessed.', on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='core.workspace')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ApiClientKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='An optional label, useful when a client has multiple keys.', max_length=100)),
                ('prefix', models.CharField(db_index=True, help_text='The public, non secret part of the key. Used to look up the key before verifying the secret.', max_length=8, unique=True)),
                ('hashed_secret', models.CharField(help_text='The hash of the secret part of the key.', max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_used_on', models.DateTimeField(blank=True, help_text='When this key was last used to authenticate a request.', null=True)),
                ('expires_on', models.DateTimeField(blank=True, help_text='After this moment the key is rejected. Null means it never expires.', null=True)),
                ('revoked_on', models.DateTimeField(blank=True, help_text='When set, the key is rejected.', null=True)),
                ('api_client', models.ForeignKey(help_text='The API client this key authenticates as.', on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='core.apiclient')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The human readable name of the schedule.', max_length=100)),
                ('cron', models.CharField(help_text='A five field crontab expression (minute hour day_of_month month day_of_week) describing when the backup runs.', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text='The timezone the cron expression is evaluated in.', max_length=64)),
                ('application_ids', models.JSONField(blank=True, default=None, help_text='The applications to back up. Null means every application of the workspace.', null=True)),
                ('only_structure', models.BooleanField(default=False, help_text='If true the backup contains the structure but not the row data.')),
                ('keep_last', models.PositiveIntegerField(blank=True, default=None, help_text='Only keep this many of the most recent backups made by this schedule. Null disables count based retention.', null=True)),
                ('keep_days', models.PositiveIntegerField(blank=True, default=None, help_text='Delete backups made by this schedule that are older than this many days. Null disables age based retention.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive schedules are skipped by the periodic task.')),
                ('next_run_on', models.DateTimeField(db_index=True, help_text='The next moment this schedule is due.')),
                ('last_run_on', models.DateTimeField(blank=True, help_text='The last moment this schedule started a backup.', null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='The error of the last failed run, empty when the last run was fine.')),
                ('user', models.ForeignKey(help_text='The user the scheduled backups are performed on behalf of.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace that is backed up.', on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='core.workspace')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
