# Generated by Django 5.2.17 on 2026-09-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_api_clients_and_backup_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupschedule',
            name='destination',
            field=models.CharField(blank=True, default='', help_text='The name of the env-declared data destination the backups are also shipped to. Empty keeps them on the instance storage only.', max_length=100),
        ),
        migrations.CreateModel(
            name='ExportApplicationsToDestinationJob',
            fields=[
                ('exportapplicationsjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.exportapplicationsjob')),
                ('destination', models.CharField(help_text='The name of the data destination the archive is uploaded to.', max_length=100)),
                ('remote_key', models.CharField(blank=True, default='', help_text='The key of the uploaded archive, relative to the destination prefix.', max_length=512)),
                ('backup_schedule', models.ForeignKey(blank=True, help_text='The schedule that started the backup, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.backupschedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.exportapplicationsjob',),
        ),
    ]
