# Generated by Django 5.2.17 on 2026-09-15 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_audit_log_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='core_auditl_created_441a84_idx',
            old_name='core_auditl_created_9c5e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='core_auditl_user_id_1f53de_idx',
            old_name='core_auditl_user_id_1f2a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='core_auditl_workspa_2e9497_idx',
            old_name='core_auditl_workspa_4d6b7e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='core_auditl_action__bbe20d_idx',
            old_name='core_auditl_action__8a1f2d_idx',
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='action_type',
            field=models.CharField(db_index=True, help_text="The registered ActionType.type, or a synthetic event name such as 'sign_in_failed' or 'sign_out'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='command_type',
            field=models.CharField(choices=[('DO', 'DO'), ('UNDO', 'UNDO'), ('REDO', 'REDO'), ('AUTH', 'AUTH')], help_text='Whether the action was done, undone, redone, or is a synthetic auth event.', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='The raw action parameters, kept for audits that need detail beyond the description.'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A human readable description of the action.'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='The IP address the request originated from, if known.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user that performed the action. Null if the user was deleted or the action could not be attributed to an authenticated user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='user_email',
            field=models.CharField(blank=True, default='', help_text="A snapshot of the user's email at the time of the action, so the entry stays meaningful after the user is deleted.", max_length=254),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace the action was performed in, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workspace'),
        ),
    ]
